version: '3.3'
services:
  db:
    image: mariadb
    container_name: mariaDB
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: escola
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
